name: Test

on:
  push:
    branches:
      - habaitica-main
  pull_request:
    branches:
      - habaitica-main

permissions:
  contents: read

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: sudo apt-get update && sudo apt-get install -y libkrb5-dev
      - run: cp config.json.example config.json
      - run: npm ci
        env:
          CI: true
          NODE_ENV: test
      - run: npm run lint-no-fix

  common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: sudo apt-get update && sudo apt-get install -y libkrb5-dev
      - run: cp config.json.example config.json
      - run: npm ci
        env:
          CI: true
          NODE_ENV: test
      - run: npm run test:common

  api-v3-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'
          mongodb-replica-set: rs
      - run: sudo apt-get update && sudo apt-get install -y libkrb5-dev
      - run: cp config.json.example config.json
      - run: npm ci
        env:
          CI: true
          NODE_ENV: test
      - run: npm run test:api-v3:integration
        env:
          REQUIRES_SERVER: 'true'

  api-v4-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '7.0'
          mongodb-replica-set: rs
      - run: sudo apt-get update && sudo apt-get install -y libkrb5-dev
      - run: cp config.json.example config.json
      - run: npm ci
        env:
          CI: true
          NODE_ENV: test
      - run: npm run test:api-v4:integration
        env:
          REQUIRES_SERVER: 'true'
